### ISSUE TITLE
Thanks for the great tool

### ISSUE THREAD

**Issue by xihajun** [jcubic/fake-linux#2]
Just want to say it is a great tool. 

May I kindly ask how does those work for `cd`?

Is it like a tree structure?

**Comment by jcubic** [comment]
Thanks. It is using in browser file system. [Lighthing-fs](https://github.com/isomorphic-git/lightning-fs) library that is part of [isomophic-git](https://isomorphic-git.org/).

The filesystem is compressed into an image.z file. So if you want more files you can put them into root directory and run `make` to create a filesystem file. THe script `make-image.js` create those images, that can be loaded.

I should probably write some instructions on how it works.

**Comment by xihajun** [comment]
Thanks for your guidance!!
